### ISSUE TITLE
Is there a way to have a one-page as a home and list of posts to an specific blog section?

### ISSUE THREAD

**Issue by albertosgz** [ktquez/vuepress-theme-ktquez#2]
Hello. Your theme looks very awesome, thanks!
My idea is to use it as a one-page for a personal project, and I would like to use vuepress with your theme as a one-page site with blog section. Can I? How?

**Comment by ktquez** [comment]
@albertosgz 
Of course, man. Feel free to use it! If you have any fixes or improvements, we accept pull-request as well.
Thanks for using.
