### ISSUE TITLE
can I add a gitlab icon in author page?

### ISSUE THREAD

**Issue by AnasR7** [ktquez/vuepress-theme-ktquez#3]
Hi Dude!, your project theme for vuepress is awesome!

can you help me to put some icon for my gitlab account in author page?

thanks.

**Comment by ktquez** [comment]
@AnasR7 
The gitlab icon I think at the moment is not dynamic, but you can use the `github` key and put the link of your gitlab. 

Example in this link: 
https://raw.githubusercontent.com/ktquez/ktquez.com/master/src/autores/ktquez.md

I'll try this weekend to see if I can make that part of the icons more dynamic.

Thanks for using.

**Comment by AnasR7** [comment]
Okay, thanks,
dude!.
