### ISSUE TITLE
Responsive post cover doesnt appear in post.

### ISSUE THREAD

**Issue by AnasR7** [ktquez/vuepress-theme-ktquez#4]
hey, I'm again sorry I have a problem with Upload image in post.
when I set in a public folder and create folder year & month and makes a responsive image is still not found, I have set cover: true and already set responsive section like in your setting and still got nothing.

![screenshot_2019-01-20_14-32-37](https://user-images.githubusercontent.com/23519166/51436470-33363580-1cc0-11e9-869c-6cb6c9947c60.png)

can you help me?
thanks

**Comment by ktquez** [comment]
Can you put your project in a repository on Github?
I can see how you are and I can help you better.

**Comment by AnasR7** [comment]
> Can you put your project in a repository on Github?
> I can see how you are and I can help you better.

you can see in my [repository,](https://gitlab.com/indiepost/indiepost.gitlab.io) sorry maybe I have a mistake or not to understand your code, I'm still learning btw

thanks for fast respond.

**Comment by AnasR7** [comment]
I'm sorry is my mistake, I have a different name of my images and my post
thanks for your help.

**Comment by ktquez** [comment]
Glad you got it, I was going to see your repository this week.

Thanks for using.
