### ISSUE TITLE
NaN date on card and Post page

### ISSUE THREAD

**Issue by gabrielboliveira** [ktquez/vuepress-theme-ktquez#5]
First of all, thanks for sharing this beautiful theme!

I found a bug on Safari, regarding how time is parsed. All dates are `NaN`, see picture to understand more:

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/11093090/51786596-a111af80-214d-11e9-93f3-74a185ca868b.png">

Same page on Chrome:

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/11093090/51786611-d4ecd500-214d-11e9-82fb-af734d39b649.png">

Operating System: macOS Mojave 10.14.2
Browser Version: Safari 12.0.2

**Comment by ktquez** [comment]
Thanks for the alert @gabrielboliveira.
I'll check what can be, fix and update the theme.

**Comment by ktquez** [comment]
@gabrielboliveira 
Can you upgrade to [v0.2.14](https://github.com/ktquez/vuepress-theme-ktquez/tree/v0.2.14) and see if it is fixed?

**Comment by gabrielboliveira** [comment]
@ktquez Looks like it caused a different bug:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/11093090/52919013-6dedb680-32dc-11e9-8c7b-092ea6ce7095.png">
