### ISSUE TITLE
My blog can't not load disqus.

### ISSUE THREAD

**Issue by CheolHoJung** [ktquez/vuepress-theme-ktquez#7]
![disqus-issue](https://user-images.githubusercontent.com/20346837/53002647-7e369a80-3470-11e9-85e5-f03a39f3380d.PNG)

I config my disqus shortname but, Disqus is not loaded.

**Comment by ktquez** [comment]
Thanks for PR!
Sorry for the delay in approving.

**Comment by ktquez** [comment]
The identifier can not be static.

The vue-disqus plugin already automatically picks up the current route.
https://github.com/ktquez/vue-disqus/blob/master/src/vue-disqus.vue#L76

**Comment by CheolHoJung** [comment]
Ah, Thank you.
